### ISSUE TITLE
Donation of Chatwood pro account

### ISSUE THREAD

**Issue by t4ggeek** [t4glabs/echolearn#1]
I had sent the following email to them. if you could check with their founder.

Dear Chatwood Team,

**chatwood registered email - hello@echolearn.org**

We recently started using chatwoot on echolearn.org - a free lifelong learning platform for changemakers. Its imagined as a forever free platform encouraging non profits to share their collective wisdom for the benefit of all.

You can read more about ust at https://www.echolearn.org/about 

We heard about you in the fossunited telegram group. 

Sincerely,
Shemeer & echo.learn( ) Team

**Comment by fossdot** [comment]
@t4ggeek Sure, I'll ping the team and will update you.
Btw, it's Chatwoot not Chatwood :D

**Comment by t4ggeek** [comment]
This is closed. They have upgraded us! :) thank you
