### ISSUE TITLE
Duplicates in 'Course Lesson List'

### ISSUE THREAD

**Issue by Pooja-Thyagi** [t4glabs/echolearn#10]
<img width="1123" alt="Screenshot 2021-11-02 at 12 23 01 PM" src="https://user-images.githubusercontent.com/92105988/139799724-222bed4e-8c02-4b60-aaba-4cc5baf057e4.png">
<img width="1123" alt="Screenshot 2021-11-02 at 12 22 46 PM" src="https://user-images.githubusercontent.com/92105988/139799750-d03a9345-b350-4fcc-b1df-ea230838520b.png">

**Comment by fossdot** [comment]
What is the total no. of lessons you see on this list? I can see **36**.

@Pooja-Thyagi I can't see the duplicates:

![Screenshot 2021-11-02 at 13-00-53 Course Lesson](https://user-images.githubusercontent.com/25725389/139804110-99bc2443-2c9a-49f0-8ee4-868f16843d11.png)

**Comment by Pooja-Thyagi** [comment]
Yeah, its not showing now for me as well!

**Comment by fossdot** [comment]
Does this mean that the issue is resolved (somehow ^-^)?

**Comment by Pooja-Thyagi** [comment]
lol I guess xP will reopen if it comes up again!
