### ISSUE TITLE
Help section not responding

### ISSUE THREAD

**Issue by Pooja-Thyagi** [t4glabs/echolearn#11]
Help section under 'New Course Lesson' does not open

<img width="1307" alt="Screenshot 2021-11-02 at 12 29 18 PM" src="https://user-images.githubusercontent.com/92105988/139800415-a7a6204a-3998-4213-a118-57c4db5e75bf.png">

**Comment by fossdot** [comment]
The latest update should fix this issue. 
Currently, we are facing another issue with the deployment. Once it's fixed, the Help section will be visible as well.

**Comment by fossdot** [comment]
This is fixed. now
